projectName: hie-botswana
image: itechuw/hie-botswana:v1.1.0-beta.1
logPath: /tmp/logs

packages:
  # I-TECH
  - client-registry-opencr
  - fhir-datastore-hapi-fhir
  - identity-access-manager-keycloak
  - interoperability-layer-openhim
  - message-bus-kafka
  - monitoring
  - reverse-proxy-nginx
  - shared-health-record
  - openhim-mediator-fhir-converter
  - openhim-mediator-omang-service
  - reverse-proxy-traefik
  
  # Future
  # - dashboard-visualiser-kibana
  # - data-mapper-logstash
  # - dashboard-visualiser-jsreport
  # - kafka-mapper-consumer
  # - kafka-unbundler-consumer
  # - analytics-datastore-clickhouse
  # - dashboard-visualiser-superset
  # - analytics-datastore-elastic-search
  
  # Possibly Needed
  # - message-bus-helper-hapi-proxy
  # - job-scheduler-ofelia
  # - openhim-mapping-mediator

# profiles:
#     - name: <<profile-name>>
#       packages:
#         - <<profile-package-id-1>>
#         - <<profile-package-id-2>>
#       envVars:
#         - <<env-var-1>>
#         - <<env-var-2>>
#       envFiles:
#         - <<env-file-1>>
#         - <<env-file-2>>
profiles:
    - name: dev
      packages:
        - reverse-proxy-traefik
        - fhir-datastore-hapi-fhir
        - identity-access-manager-keycloak
        - interoperability-layer-openhim
        - client-registry-opencr
        - message-bus-kafka
        - openhim-mediator-omang-service
        - shared-health-record
        - openhim-mediator-fhir-converter
        - message-bus-kafka
        - monitoring
      envFiles:
        - .env.hie
      dev: false
      only: false
      
    - name: omang
      packages:
        - reverse-proxy-traefik
        - interoperability-layer-openhim
      envFiles:
        - .env.hie
      dev: false
      only: false