projectName: hie-botswana
image: i-tech-uw/hie-botswana:v0.6.0
logPath: /tmp/logs

packages:
  # I-TECH
  - client-registry-opencr
  - shared-health-record
  - reverse-proxy-caddy
  - openhim-mediator-omang-service
  - openhim-mediator-fhir-translator

  # From https://github.com/jembi/platform
  - interoperability-layer-openhim
  - fhir-datastore-hapi-fhir
  - message-bus-kafka
  - analytics-datastore-elastic-search
  - monitoring
  - identity-access-manager-keycloak
  
  # Future
  # - dashboard-visualiser-kibana
  # - data-mapper-logstash
  # - dashboard-visualiser-jsreport
  # - kafka-mapper-consumer
  # - kafka-unbundler-consumer
  # - analytics-datastore-clickhouse
  # - dashboard-visualiser-superset
  
  # Possibly Needed
  # - message-bus-helper-hapi-proxy
  # - job-scheduler-ofelia
  # - openhim-mapping-mediator

# profiles:
#     - name: <<profile-name>>
#       packages:
#         - <<profile-package-id-1>>
#         - <<profile-package-id-2>>
#       envVars:
#         - <<env-var-1>>
#         - <<env-var-2>>
#       envFiles:
#         - <<env-file-1>>
#         - <<env-file-2>>
