version: '3.8'

## Port Assignments:
##  See .env file

## Container debugging:
# 1. append the following lines to desired container
# 2. boot up the container using `docker-compose up -d`
# 3 run `docker exec -it <container-name> bash` to start interactive shell
#
#    tty: true
#    stdin_open: true
#    entrypoint: bash

services:
  caddy:
    container_name: caddy
    image: lucaslorentz/caddy-docker-proxy:latest
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=hie
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy-data:/data
    restart: unless-stopped
    networks:
      - hie

  # certbot:
  #   image: certbot:local
  #   container_name: certbot
  #   environment:
  #   - AWS_ACCESS_KEY_ID
  #   - AWS_SECRET_ACCESS_KEY
  #   - EMAIL
  #   - ROOT_URL
  #   volumes:
  #   - certs:/etc/letsencrypt
  #   - letsencrypt:/var/lib/letsencrypt
  #   networks:
  #   - hie
  
  ###
  # OpenCR
  ###
  opencr:
    container_name: opencr
    hostname: opencr
    image: intrahealth/opencr:latest #76efe76
    restart: unless-stopped
    environment:
      - NODE_ENV=docker
      - HAPI_FHIR_URL=http://opencr-fhir:8080/fhir/metadata
    networks:
      - hie
    volumes:
      - ./configs/opencr/config.json:/src/server/config/config_docker.json
      - ./configs/opencr/mediator.json:/src/server/config/mediator.json
      - ./configs/opencr/decisionRules.json:/src/server/config/decisionRules.json
      - ./configs/opencr/PatientRelationship.json:/src/resources/Relationships/PatientRelationship.json
    labels:
      caddy: opencr.bwhie.org
      caddy.reverse_proxy: "{{ upstreams 3000 }}"

      
  opencr-fhir:
    image: hapiproject/hapi:v5.1.0
    container_name: opencr-fhir
    hostname: opencr-fhir
    restart: unless-stopped
    networks:
      - hie
    healthcheck:
      test: "curl -sS http://opencr-fhir:8080/fhir/metadata || exit 1"
      interval: 90s
      timeout: 30s
      retries: 3
    ports:
      - 8082:8080
    volumes:
      - cr-data:/data/hapi

  es:
    container_name: es
    hostname: es
    image: intrahealth/elasticsearch:latest
    restart: unless-stopped
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    networks:
      - hie
    healthcheck:
      test: "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"

  ###
  # SHR
  ###
  shr:
    container_name: shr
    hostname: shr
    image: ghcr.io/i-tech-uw/shared-health-record:${SHR_VERSION-latest}
    restart: unless-stopped
    environment:
      - NODE_ENV=docker
    networks:
      - hie
    volumes:
      - ./configs/shr/config.json:/app/config/config_docker.json
      - ./configs/shr/mediator.json:/app/config/mediator_docker.json

  shr-fhir:
    image: hapiproject/hapi:latest-tomcat
    container_name: shr-fhir
    hostname: shr-fhir
    restart: unless-stopped
    volumes:
      - shr-data:/data/hapi
      # - ./configs/shr/application.yaml:/data/hapi/application.yaml
    environment:
      SPRING_CONFIG_LOCATION: 'file:///data/hapi/application.yaml'
    ports:
      - 8080:8080
    networks:
      - hie
    healthcheck:
      test: "curl -sS http://shr-fhir:8080/fhir/metadata || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
    

  ###
  # OpenHIM
  ###
  openhim-core:
    container_name: openhim-core
    hostname: openhim-core
    image: jembi/openhim-core:latest
    restart: unless-stopped
    environment:
      mongo_url: "mongodb://mongo-db/openhim"
      mongo_atnaUrl: "mongodb://mongo-db/openhim"
      NODE_ENV: "development"
    healthcheck:
      test: "node /healthcheck.js"
      interval: 20s
      timeout: 20s
      retries: 2
    networks:
      - hie
    volumes:
      - ./configs/openhim/healthcheck.js:/healthcheck.js
      - ./configs/openhim/config.json:/app/config/default.json
      - ./configs/certs:/certs
    labels:
      caddy_0: openhim-core.bwhie.org 
      caddy_0.reverse_proxy: "{{ upstreams 8080}}"
      caddy_0.reverse_proxy.transport: http
      caddy_0.reverse_proxy.transport.tls_insecure_skip_verify:
      caddy_1: openhim-ssl.bwhie.org
      caddy_1.reverse_proxy: "{{ upstreams 5000 }}"
      caddy_1.reverse_proxy.transport: http
      caddy_1.reverse_proxy.transport.tls_insecure_skip_verify:
      caddy_2: http://openhim-http.bwhie.org
      caddy_2.reverse_proxy: "{{ upstreams 5001 }}"

    ports:
      - 5000:5000
      - 5001:5001

  openhim-console:
    container_name: openhim-console
    hostname: openhim-console
    image: jembi/openhim-console:latest
    restart: unless-stopped
    volumes:
      - ./configs/openhim-console/default.json:/usr/share/nginx/html/config/default.json
    healthcheck:
      test: "curl -sS http://openhim-console || exit 1"
      interval: 10s
      timeout: 60s
      retries: 3
    labels:
      caddy: bwhie.org
      caddy.reverse_proxy: "{{ upstreams 80 }}"

    networks:
      - hie

  # Loads Default OpenHIM Config
  openhim-config:
    container_name: openhim-config
    image: ghcr.io/i-tech-uw/openhim-config:v0.0.0
    volumes:
      - ./configs/openhim/test-openhim-config.json:/app/test-openhim-config.json
    networks:
      - hie

  mongo-db:
    container_name: mongo-db
    image: mongo:3.4
    volumes:
      - "mongo-data:/data/db"
    restart: unless-stopped
    networks:
      - hie

  fhir-converter:
    container_name: fhir-converter
    hostname: fhir-converter
    restart: unless-stopped
    image: ghcr.io/i-tech-uw/openhim-mediator-fhir-converter:${FHIR_CONVERTER_VERSION-latest}
    volumes:
      - ./configs/fhir-converter/config.json:/app/config.json
      - /app/src/service-templates
    networks:
      - hie
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.converter.tls.certresolver=${PROVIDER}"
      - 'traefik.docker.network=hie-botswana_hie'
      - 'traefik.http.routers.converter.tls=true'
      - 'traefik.http.routers.converter.entrypoints=web-secure'
      - 'traefik.http.routers.converter.rule=Host(`converter.${ROOT_URL}`)'

  # Kafka
  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: zookeeper
    restart: unless-stopped
    hostname: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
    - hie
    volumes:
      - /data
  kafka:
    image: "bitnami/kafka:latest"
    hostname: kafka
    container_name: kafka
    restart: unless-stopped
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
    - hie
    entrypoint: sh -c 'sleep 30 && /opt/bitnami/scripts/kafka/entrypoint.sh /opt/bitnami/scripts/kafka/run.sh' # prevent zookeeper conflict error
  
  omang-api:
    image: ghcr.io/i-tech-uw/omangsvc:${OMANG_SVC_VERSION-latest}
    hostname: omang-api
    container_name: omang-api
    restart: unless-stopped
    volumes:
      - ./configs/omang/appsettings.json:/app/appsettings.json
    networks:
      - hie
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.omang.tls.certresolver=${PROVIDER}"
      - 'traefik.docker.network=hie-botswana_hie'
      - 'traefik.http.routers.omang.tls=true'
      - 'traefik.http.routers.omang.entrypoints=web-secure'
      - 'traefik.http.routers.omang.rule=Host(`omang.${ROOT_URL}`)'
    environment:
      - TZ=GMT
 
  oracle-db:
    hostname: oracle-db
    container_name: oracle-db
    restart: unless-stopped
    image: wnameless/oracle-xe-11g-r2:latest
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - TZ=GMT
    ports:
      - 1521:1521
    volumes:
      - ./configs/omang/db:/docker-entrypoint-initdb.d

    networks:
      - hie
volumes:
  es:
    driver: local
  mongo-data:
    driver: local
  sqldata:
    driver: local
  shr-data:
    driver: local
  cr-data:
    driver: local
  certs:
    driver: local
  kafka-data:
    driver: local
  letsencrypt:
    driver: local
  caddy-data: {}
networks:
  hie:
    name: hie
