  oracle-db:
    hostname: oracle-db
    container_name: oracle-db
    restart: unless-stopped
    image: wnameless/oracle-xe-11g-r2:latest
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - TZ=GMT
    ports:
      - 1521:1521
    volumes:
      - ./configs/omang/db:/docker-entrypoint-initdb.d

    networks:
      - hie