version: '3.9'
services:  
  oracle-db:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    image: wnameless/oracle-xe-11g-r2:latest
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - TZ=GMT
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    networks:
      - default
      - oracle
networks:
  default:
  oracle:
    external: true
    name: oracle
    