version: '3.9'

services:
  shared-health-record:
    image: ghcr.io/i-tech-uw/shared-health-record:${SHR_VERSION-latest}
    environment:
      - NODE_ENV=docker
    networks:
      - default
      - hapi-fhir
      - shr
      - kafka
    configs:
      - source: shr_config
        target: /app/config/config_docker.json
      - source: shr_mediator
        target: /app/config/mediator_docker.json
configs:
  shr_config:
    file: ./config/config.json
  shr_mediator:
    file: ./config/mediator.json

networks:
  default:
  kafka:
    external: true
    name: kafka_public
  hapi-fhir:
    external: true
    name: hapi-fhir_public
  shr:
    name: shr_public
    external: true
  default:
