services:
  shared-health-record:
    image: itechuw/shared-health-record:v0.13.0
    networks:
      - default
      - hapi-fhir
      - shr
      - kafka
      - opencr
      - ocl
    ports:
      - "3001:3001"
      - "3002:3001"
    configs:
      - source: shr_config
        target: /app/config/config_docker.json
      - source: shr_mediator
        target: /app/config/mediator_docker.json
      - source: ipms_locations
        target: /app/config/ipms_facility_mappings.xlsx
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
configs:
  shr_config:
    file: ./config/_config.json
    labels:
      name: shr
  shr_mediator:
    file: ./config/mediator.json
    labels:
      name: shr
  ipms_locations:
    file: ./config/ipms_facility_mappings.xlsx
    labels:
      name: shr 

networks:
  default:
  kafka:
    external: true
    name: kafka_public
  hapi-fhir:
    external: true
    name: hapi-fhir_public
  shr:
    name: shr_public
    external: true
  opencr:
    name: opencr
    external: true
  openhim:
    name: openhim_public
    external: true
  ocl:
    name: reverse-proxy-ocl_public
    external: true
