services:
  shared-health-record:
    image: itechuw/shared-health-record:dev
    entrypoint: node --inspect=0.0.0.0:9230 /app/dist/app.js
    
    ports:
      - target: 9230
        published: 9230
        mode: host
